<?php

namespace AppBundle\Repository;

/**
 * ProblematicaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProblematicaRepository extends \Doctrine\ORM\EntityRepository
{
}
