<?php

namespace AppBundle\Repository;

/**
 * TipoProblematicaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoProblematicaRepository extends \Doctrine\ORM\EntityRepository
{
}
